
use kdt;

CREATE TABLE `TB_CALENDAR` (
	`C_NUM`	INT	NOT NULL,
	`U_NUM`	INT	NOT NULL,
	`C_TITLE`	VARCHAR(255) NOT NULL,
	`C_START`	DATE NOT NULL,
	`C_END`	DATE NOT NULL,
	`C_CONTENT`	VARCHAR(255)	NULL,
	`C_COLOR`	VARCHAR(255)	NULL
);

# 일정 가져오기
SELECT C_NUM, U_NUM, C_TITLE, C_START, C_END, C_CONTENT, C_COLOR FROM TB_CALENDAR;

-- # 일정 클릭
-- SELECT C_NUM, U_NUM, C_TITLE, C_START, C_END, C_CONTENT, C_COLOR FROM TB_CALENDAR WHERE DATE = '클릭할일정';

# 일정 삽입
INSERT INTO TB_CALENDAR(C_TITLE, C_START, C_END, C_CONTENT, C_COLOR) VALUES ('입력할제목', '입력할시작날짜', '입력할마감날짜', '입력할내용', '입력할색깔');  

# 일정 삭제
DELETE FROM TB_CALENDAR WHERE C_NUM='클릭할일정';

# 일정 수정
UPDATE TB_CALENDAR SET C_TITLE='수정할제목', C_START='수정할시작날짜', C_END='수정할마감날짜', C_CONTENT='수정할내용', C_COLOR='수정할색깔' WHERE C_NUM='클릭할일정';




-- ============================================================================================================================-- 

use kdt;
CREATE TABLE `TB_USER` (
	`U_NUM`	INT	AUTO_INCREMENT PRIMARY KEY,
	`U_ID`	VARCHAR(20)	NOT NULL,
	`U_PW`	VARCHAR(20)	NOT NULL,
	`U_NAME`	VARCHAR(20),
	`U_EMAIL`	VARCHAR(50)	NOT NULL,
	`U_ZIP_CODE`	VARCHAR(50),
	`U_ADDRESS1`	VARCHAR(50),
	`U_ADDRESS2`	VARCHAR(50),
	`U_DATE_JOIN`	DATETIME	DEFAULT	NOW(),
	`U_ID_TYPE`	VARCHAR(5),
    `U_HP` VARCHAR(12)
);
INSERT INTO TB_USER(U_NUM,U_ID,U_PW,U_NAME,U_EMAIL,U_ZIP_CODE,U_ADDRESS1,U_ADDRESS2,) VALUES ('입력할제목');
CREATE TABLE `TB_QNA` (
	`Q_NUM`		INT	AUTO_INCREMENT PRIMARY KEY,
	`U_NUM`		INT	NOT NULL,
	`Q_TITLE`	VARCHAR(50)	NOT NULL,
	`Q_CONTENT`	VARCHAR(500)	NOT NULL,
	`Q_ANSWER`	BOOLEAN	NOT NULL,
	`Q_DATE`	DATETIME	DEFAULT	NOW(),
    FOREIGN KEY(U_NUM) REFERENCES TB_USER(U_NUM)
);
CREATE TABLE `TB_ANNOUNCEMENT` (
	`A_NUM`	INT	AUTO_INCREMENT PRIMARY KEY,
	`U_NUM`	INT	NOT NULL,
	`A_TITLE`	VARCHAR(50)	NOT NULL,
	`A_DATE`	DATETIME	DEFAULT	NOW(),
	`A_WRITER`	VARCHAR(50)	NOT NULL,
	`A_CONTENT`	VARCHAR(500)	NOT NULL,
    FOREIGN KEY(U_NUM) REFERENCES TB_USER(U_NUM)
);



-- ============================================================================================================================-- 



## 관리자 페이지 -> 약품 관리
desc tb_medicine;
INSERT INTO tb_medicine (M_NUM,M_NAME,M_CORP,M_TYPE,M_SHAPE,M_REGDATE,M_MARK_FRONT,M_MARK_BACK
,M_COLOR_FRONT,M_COLOR_BACK,M_CHARACTER,M_AXIS_LONG,M_AXIS_SHORT,M_THICKNESS,M_IMAGE)
values (?,?,?,?,?,?,?,?,?,?,?,?,?,?);
## SELECT ALL(약품관리 기본화면)
SELECT M_NUM,M_NAME,M_CORP,M_TYPE from tb_medicine order by M_Num asc limit 0,9;
## select ONE (약품관리 모달창)
SELECT M_NUM,M_NAME,M_CORP,M_TYPE,M_SHAPE,M_REGDATE,M_MARK_FRONT,M_MARK_BACK
,M_COLOR_FRONT,M_COLOR_BACK,M_CHARACTER,M_AXIS_LONG,M_AXIS_SHORT,M_THICKNESS,M_IMAGE
FROM tb_medicine where M_Num='?';
UPDATE tb_medicine SET M_NUM=?,M_NAME=?,M_CORP=?,M_TYPE=?,M_SHAPE=?,M_REGDATE=?,M_MARK_FRONT=?,M_MARK_BACK=?
,M_COLOR_FRONT=?,M_COLOR_BACK=?,M_CHARACTER=?,M_AXIS_LONG=?,M_AXIS_SHORT=?,M_THICKNESS=?,M_IMAGE=?
WHERE M_Num='?';
DELETE FROM tb_medicine WHERE M_Num='?';
#=========================================================================#
### 약국 관리
## SELECT ALL (약국관리 기본화면)
select P_NUM,P_NAME,P_ADDRESS from tb_pharm  order by M_Num asc limit 0,9;
### SELECT ONE (약국관리 모달창)
SELECT P_NUM,P_NAME,P_PHONE,P_LATI,P_LONGI,P_ADDRESS,P_MON_S,P_MON_C,P_TUE_S,P_TUE_C,P_WED_S,P_WED_C,P_THU_S,P_THU_C,
P_FRI_S,P_FRI_C,P_SAT_S,P_SAT_C,P_SUN_S,P_SUN_C,P_HOLI_S,P_HOLI_C FROM tb_pharm;
## 데이터 추가
INSERT INTO tb_pharm (P_NUM,P_NAME,P_PHONE,P_LATI,P_LONGI,P_ADDRESS,P_MON_S,P_MON_C,P_TUE_S,P_TUE_C,P_WED_S,P_WED_C,
P_THU_S,P_THU_C,P_FRI_S,P_FRI_C,P_SAT_S,P_SAT_C,P_SUN_S,P_SUN_C,P_HOLI_S,P_HOLI_C)
values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);
UPDATE tb_pharm SET P_NUM=?,P_NAME=?,P_PHONE=?,P_LATI=?,P_LONGI=?,P_ADDRESS=?,P_MON_S=?,P_MON_C=?,P_TUE_S=?,P_TUE_C=?,
P_WED_S=?,P_WED_C=?,P_THU_S=?,P_THU_C=?,P_FRI_S=?,P_FRI_C=?,P_SAT_S=?,P_SAT_C=?,P_SUN_S=?,P_SUN_C=?,P_HOLI_S=?
,P_HOLI_C=? WHERE P_NUM='?';
DELETE FROM tb_pharm WHERE P_NUM='?';
#=========================================================================#

-- ============================================================================================================================-- 





# 회원 관리 메인 (관리자페이지)
SELECT U_NUM, U_ID, U_NAME, U_EMAIL FROM TB_USER ORDER BY U_NUM ASC LIMIT 0,9;
# 회원 관리 모달 (관리자페이지)
SELECT U_NUM, U_ID, U_NAME, U_EMAIL, U_HP FROM TB_USER;
# 회원 관리 수정 (관리자페이지)
UPDATE TB_USER SET U_NUM=?, U_ID=?, U_NAME=?, U_EMAIL=?, U_HP=? WHERE U_NUM='?';
# 회원 관리 삭제 (관리자페이지)
DELETE FROM TB_USER WHERE U_NUM='?';

# 공지사항 메인 (관리자페이지)
SELECT AN.A_NUM, AN.A_TITLE, US.U_NAME, AN.A_DATE FROM TB_ANNOUNCEMENT AS AN JOIN TB_USER AS US ON AN.U_NUM=US.U_NUM ORDER BY AN.A_NUM ASC;
# 공지사항 작성 (관리자페이지)
INSERT INTO TB_ANNOUNCEMENT(A_TITLE) VALUES ('입력할제목');
INSERT INTO TB_USER(U_NAME) VALUES ('입력할이름');
INSERT INTO TB_ANNOUNCEMENT(A_CONTENT) VALUES ('입력할내용');
# 공지사항 수정 (관리자페이지)
UPDATE TB_ANNOUNCEMENT AS AN
JOIN TB_USERS AS US 
ON AN.A_NUM=US.U_NUM 
SET AN.A_TITLE='?', US.U_NAME='?', AN.A_DATE='?', AN.A_CONTENT='?';
# 공지사항 삭제 (관리자페이지)
DELETE FROM TB_ANNOUNCEMENT WHERE A_NUM='?';
# 공지사항 모달 (관리자페이지) / 입력
INSERT INTO TB_ANNOUNCEMENT(A_TITLE) VALUES ('입력할제목');
INSERT INTO TB_USER(U_NAME) VALUES ('입력할이름');
INSERT INTO TB_ANNOUNCEMENT(A_DATE) VALUES (DATETIME);
INSERT INTO TB_ANNOUNCEMENT(A_CONTENT) VALUES ('입력할내용');

# 문의사항 메인 (관리자페이지)
SELECT QA.Q_ANSWER, QA.Q_NUM, QA.Q_TITLE, US.U_NAME, QA.Q_DATE FROM TB_USER AS US INNER JOIN TB_QNA AS QA ON US.U_NUM = QA.U_NUM ORDER BY QA.Q_NUM ASC;
# 문의 내역
SELECT Q_TITLE FROM TB_QNA WHERE Q_NUM = '?';
# 답변 삽입
UPDATE TB_QNA SET Q_CONTENT='답변내용' WHERE Q_ANSWER = FALSE;
-- ============================================================================================================================-- 
CREATE DATABASE MEDIMATE;
USE MEDIMATE;

CREATE TABLE `TB_USER` (
	`U_NUM`	INT	AUTO_INCREMENT PRIMARY KEY,
	`U_ID`	VARCHAR(20)	NOT NULL,
	`U_PW`	VARCHAR(20)	NOT NULL,
	`U_NAME`	VARCHAR(20),
	`U_EMAIL`	VARCHAR(50)	NOT NULL,
	`U_ZIP_CODE`	VARCHAR(50),
	`U_ADDRESS1`	VARCHAR(50),
	`U_ADDRESS2`	VARCHAR(50),
	`U_DATE_JOIN`	DATETIME	DEFAULT	NOW(),
	`U_ID_TYPE`	VARCHAR(5),
    `U_HP` VARCHAR(12)
);
INSERT INTO TB_USER(U_ID,U_PW,U_NAME,U_EMAIL,U_ZIP_CODE,U_ADDRESS1,U_ADDRESS2,U_ID_TYPE,U_HP) VALUES ('yjcho','1234','조윤재','yjcho@fow.kr','04411','서울용산','장문로51길','일반회원','01065985755');
INSERT INTO TB_USER(U_ID,U_PW,U_NAME,U_EMAIL,U_ZIP_CODE,U_ADDRESS1,U_ADDRESS2,U_ID_TYPE,U_HP) VALUES ('ydceho','1234','조윤재','yjcho@fow.kr','04411','서울용산','장문로51길','일반회원','01065985755');
INSERT INTO TB_USER(U_ID,U_PW,U_NAME,U_EMAIL,U_ZIP_CODE,U_ADDRESS1,U_ADDRESS2,U_ID_TYPE,U_HP) VALUES ('yscfo','1234','조윤재','yjcho@fow.kr','04411','서울용산','장문로51길','일반회원','01065985755');
INSERT INTO TB_USER(U_ID,U_PW,U_NAME,U_EMAIL,U_ZIP_CODE,U_ADDRESS1,U_ADDRESS2,U_ID_TYPE,U_HP) VALUES ('yacdso','1234','조윤재','yjcho@fow.kr','04411','서울용산','장문로51길','일반회원','01065985755');
select * from tb_user;

CREATE TABLE `TB_PHARM` (
	`P_NUM`		VARCHAR(20)	PRIMARY KEY,
	`P_NAME`	VARCHAR(20)	NOT NULL,
	`P_ADDRESS`	VARCHAR(20),
	`P_PHONE`	VARCHAR(20),
	`P_MON_S`	VARCHAR(20),
	`P_MON_C`	VARCHAR(20),
	`P_TUE_S`	VARCHAR(20),
	`P_TUE_C`	VARCHAR(20),
	`P_WED_S`	VARCHAR(20),
	`P_WED_C`	VARCHAR(20),
	`P_THU_S`	VARCHAR(20),
	`P_THU_C`	VARCHAR(20),
	`P_FRI_S`	VARCHAR(20),
	`P_FRI_C`	VARCHAR(20),
	`P_SAT_S`	VARCHAR(20),
	`P_SAT_C`	VARCHAR(20),
	`P_SUN_S`	VARCHAR(20),
	`P_SUN_C`	VARCHAR(20),
	`P_HOLI_S`	VARCHAR(20),
	`P_HOLI_C`	VARCHAR(20),
	`P_LATI`	VARCHAR(20),
	`P_LONGI`	VARCHAR(20)
);

CREATE TABLE `TB_CALENDAR` (
	`C_NUM`	INT	AUTO_INCREMENT PRIMARY KEY,
	`U_NUM`	INT	NOT NULL,
	`C_TITLE`	VARCHAR(255)	NOT NULL,
	`C_START`	DATE	NOT NULL,
	`C_END`	DATE	NOT NULL,
	`C_CONTENT`	VARCHAR(255),
	`C_COLOR`	VARCHAR(255),
    FOREIGN KEY(U_NUM) REFERENCES TB_USER(U_NUM)
);

CREATE TABLE `TB_QNA` (
	`Q_NUM`		INT	AUTO_INCREMENT PRIMARY KEY,
	`U_NUM`		INT	NOT NULL,
	`Q_TITLE`	VARCHAR(50)	NOT NULL,
	`Q_CONTENT`	VARCHAR(500)	NOT NULL,
	`Q_ANSWER`	BOOLEAN	NOT NULL,
	`Q_DATE`	DATETIME	DEFAULT	NOW(),
    FOREIGN KEY(U_NUM) REFERENCES TB_USER(U_NUM)
);

CREATE TABLE `TB_ANNOUNCEMENT` (
	`A_NUM`	INT	AUTO_INCREMENT PRIMARY KEY,
	`U_NUM`	INT	NOT NULL,
	`A_TITLE`	VARCHAR(50)	NOT NULL,
	`A_DATE`	DATETIME	DEFAULT	NOW(),
	`A_WRITER`	VARCHAR(50)	NOT NULL,
	`A_CONTENT`	VARCHAR(500)	NOT NULL,
    FOREIGN KEY(U_NUM) REFERENCES TB_USER(U_NUM)
);

CREATE TABLE `TB_SHARE_CALENDAR` (
	`S_NUM`	INT	PRIMARY KEY,
	`S_FOLLOWER_NUM`	INT	NOT NULL,
	`S_FOLLOWING_NUM`	INT	NOT NULL,
    FOREIGN KEY(S_FOLLOWER_NUM) REFERENCES TB_USER(U_NUM),
    FOREIGN KEY(S_FOLLOWING_NUM) REFERENCES TB_USER(U_NUM)
);

CREATE TABLE `TB_MEDICINE` (
	`M_NUM`	VARCHAR(20)	PRIMARY KEY,
	`M_NAME`	VARCHAR(50)	NOT NULL,
	`M_CORP`	VARCHAR(50)	NOT NULL,
	`M_TYPE`	BOOLEAN	NOT NULL,
	`M_SHAPE`	VARCHAR(50),
	`M_REGDATE`	DATETIME	DEFAULT	NOW(),
	`M_MARK_FRONT`	VARCHAR(10),
	`M_MARK_BACK`	VARCHAR(10),
	`M_COLOR_FRONT`	VARCHAR(10),
	`M_COLOR_BACK`	VARCHAR(10),
	`M_CHARACTER`	VARCHAR(10),
	`M_AXIS_LONG`	VARCHAR(10),
	`M_AXIS_SHORT`	VARCHAR(10),
	`M_THICKNESS`	VARCHAR(10),
	`M_IMAGE`	VARCHAR(255)
);